-- liquibase formatted sql

-- changeset script:1
-- comment: Creation table brands
create table brands (
    brand_id integer generated by default as identity,
    active boolean,
    date_creation timestamp,
    date_modification timestamp,
    user_creation varchar(50),
    user_modification varchar(50),
    brand varchar(255),
    primary key (brand_id)
);

-- changeset script:2
-- comment: Creation table currency
create table currency (
    currency_id integer generated by default as identity,
    active boolean,
    date_creation timestamp,
    date_modification timestamp,
    user_creation varchar(50),
    user_modification varchar(50),
    currency varchar(255),
    primary key (currency_id)
 );

 -- changeset script:3
 -- comment: Creation table prices
 create table prices (
    price_id integer generated by default as identity,
    active boolean,
    date_creation timestamp,
    date_modification timestamp,
    user_creation varchar(50),
    user_modification varchar(50),
    end_date timestamp,
    price double,
    price_list integer,
    priority integer,
    start_date timestamp,
    id_brand_fk integer,
    id_currency_fk integer,
    id_product_fk integer,
    primary key (price_id)
 );

 -- changeset script:4
 -- comment: Creation table products
 create table products (
    product_id integer generated by default as identity,
    active boolean,
    date_creation timestamp,
    date_modification timestamp,
    user_creation varchar(50),
    user_modification varchar(50),
    code varchar(255),
    product varchar(255),
    primary key (product_id)
);

 -- changeset script:5
 -- comment: Data table brands
INSERT INTO brands(brand, active)	VALUES
    ( 'ZARA', true);

-- changeset script:6
-- comment: Creation table tipo_de_pago
INSERT INTO currency(currency, active)	VALUES
    ( 'EUR', true),
    ( 'USD', true);

-- changeset script:7
-- comment: Data table products
INSERT INTO products(code, product, active)	VALUES
    ( 35455, 'Shirt',true),
    ( 35455, 'Pants',true);

-- changeset script:8
-- comment: Data table prices
INSERT INTO prices(id_product_fk, id_brand_fk, id_currency_fk, price_list, priority, price, start_date, end_date, active)	VALUES
    ( 1, 1, 1, 1, 0, 35.50, '2020-06-14 00:00:00', '2020-12-31 23:59:59', true),
    ( 1, 1, 1, 2, 1, 25.45, '2020-06-14 15:00:00', '2020-06-14 18:30:00', true),
    ( 1, 1, 1, 3, 1, 30.50, '2020-06-15 00:00:00', '2020-06-15 11:00:00', true),
    ( 1, 1, 1, 4, 1, 38.95, '2020-06-15 16:00:00', '2020-12-31 23:59:59', true);

